# Generated by Django 4.2.4 on 2023-08-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrainfuckProgram',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('name', models.CharField(max_length=30)),
                ('output', models.TextField()),
                ('pointer', models.IntegerField()),
                ('length', models.IntegerField()),
                ('loop_stack', models.TextField()),
                ('loop_stack_pointer', models.IntegerField()),
                ('memory_array', models.TextField()),
                ('memoryArrayPointer', models.IntegerField()),
                ('memorySize', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status_codes', models.CharField(choices=[('0', 'Running'), ('1', 'Program finished'), ('2', 'Waiting for character input'), ('3', 'Waiting for integer input'), ('4', 'Out of time')], default='Running', max_length=1)),
            ],
        ),
    ]
