# Generated by Django 4.2.4 on 2023-08-21 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brainfuckprogram',
            name='memorySize',
        ),
    ]
