# Generated by Django 4.2.4 on 2023-08-21 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_brainfuckprogram_memorysize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brainfuckprogram',
            name='length',
        ),
    ]
