# Generated by Django 4.2.4 on 2023-08-21 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_rename_memoryarraypointer_brainfuckprogram_memory_array_pointer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brainfuckprogram',
            old_name='status_codes',
            new_name='status_code',
        ),
    ]
