# Generated by Django 4.2.4 on 2023-08-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_rename_status_codes_brainfuckprogram_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brainfuckprogram',
            name='loop_stack_pointer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='brainfuckprogram',
            name='memory_array_pointer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='brainfuckprogram',
            name='output',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='brainfuckprogram',
            name='pointer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='brainfuckprogram',
            name='status_code',
            field=models.CharField(choices=[('Run', 'Running'), ('Fin', 'Finished'), ('Wfc', 'Waiting for character input'), ('Wfn', 'Waiting for numeric input'), ('Oot', 'Out of time'), ('Ool', 'Loop stack out of memory'), ('Oom', 'Out of memory'), ('Mcb', 'Missing closing brackets')], default='Run', max_length=3),
        ),
    ]
